(function(g){var window=this;var fra=function(a,b){var c=[];g.Bf(b,function(a){var b;try{b=g.Si.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.p(b)?g.Ri(b)&&c.push(a):c.push(a)},a);
return c},gra=function(a,b){var c=fra(a,b);
(0,g.H)(c,function(a){g.Si.prototype.remove.call(this,a)},a)},g9=function(a){return a.H?a.F+((0,g.G)()-a.A)/1E3:a.F},hra=function(){var a=g.Ti;
gra(a,a.g.sd(!0))},h9=function(a){g.Mz.call(this,"ScreenServiceProxy");
this.Jc=a;this.o=[];this.o.push(this.Jc.$_s("screenChange",(0,g.z)(this.FJ,this)));this.o.push(this.Jc.$_s("onlineScreenChange",(0,g.z)(this.qG,this)))},i9=function(a){g.Iz("cloudview",a)},j9=function(a){i9("setApiReady_ "+a);
g.ka("yt.mdx.remote.cloudview.apiReady_",a,void 0)},k9=function(){return g.u("yt.mdx.remote.cloudview.instance_")},l9=function(a){g.xi[a]&&(a=g.xi[a],(0,g.H)(a,function(a){g.vi[a]&&delete g.vi[a]}),a.length=0)},m9=function(){return g.u("yt.mdx.remote.connection_")},n9=function(a){g.ka("yt.mdx.remote.connectData_",a,void 0)},o9=function(a){g.ka("yt.mdx.remote.currentScreenId_",a,void 0)},p9=function(){return g.u("yt.mdx.remote.currentScreenId_")},r9=function(){if(!q9){var a=g.u("yt.mdx.remote.screenService_");
q9=a?new h9(a):null}return q9},s9=function(a){g.ka("yt.mdx.remote.cloudview.initializing_",a,void 0)},t9=function(){return!!g.u("yt.mdx.remote.cloudview.apiReady_")},u9=function(a){i9("setCastInstalled_ "+a);
g.Vi("yt-remote-cast-installed",a)},v9=function(a){g.Iz("cloudview",a)},ira=function(a,b){k9().init(a,b)},w9=function(){return!!g.Wi("yt-remote-cast-installed")},y9=function(){i9("dispose");
var a=k9();a&&a.dispose();g.ka("yt.mdx.remote.cloudview.instance_",null,void 0);j9(!1);g.zi(x9);x9.length=0},jra=function(){var a=window.document.createElement("a");
g.se(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Na(a)},kra=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},lra=function(a){var b=g.ti();
if(b)if(b.clear(a),a)l9(a);else for(var c in g.xi)l9(c)},z9=function(a,b){g.wi[a]=!0;
var c=g.ti();c&&c.publish.apply(c,arguments);g.wi[a]=!1},A9=function(a){return a?a.dataset?a.dataset[g.ah("loaded")]:a.getAttribute("data-loaded"):null},B9=function(){return g.u("yt.mdx.remote.channelParams_")||{}},D9=function(a){var b=m9();
n9(null);a||o9("");g.ka("yt.mdx.remote.connection_",a,void 0);C9&&((0,g.H)(C9,function(b){b(a)}),C9.length=0);
b&&!a?z9("yt-remote-connection-change",!1):!b&&a&&z9("yt-remote-connection-change",!0)},E9=function(){return g.u("yt.mdx.remote.connectData_")},F9=function(){var a=p9();
if(!a)return null;var b=r9().wd();return g.di(b,a)},G9=function(a,b){u9(!0);
s9(!1);ira(a,function(a){a?(j9(!0),g.Bi("yt-remote-cast2-api-ready")):(v9("Failed to initialize cast API."),u9(!1),g.Xi("yt-remote-cast-available"),g.Xi("yt-remote-cast-receiver"),y9());b(a)})},H9=function(){return w9()?k9()?k9().getCastSession():(v9("getCastSelector: Cast is not initialized."),null):(v9("getCastSelector: Cast API is not installed!"),null)},I9=function(){if(g.dqa){var a=2,b=g.xz(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.Cz("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.zz,c)}},mra=function(){var a=jra(),b=window.document.getElementById(a),c=b&&A9(b);
c||b&&!c||(b=kra(a,function(){A9(b)||(g.bh(b,"loaded","true"),g.Bi(a),g.Qg(g.B(lra,a),0))}))},nra=function(a){return(0,g.R)(a,function(a){return{key:a.id,
name:a.name}})},K9=function(a,b){p9();
F9()&&F9();o9(a.id);var c=new g.XB(J9,a,B9());c.connect(b,E9());c.subscribe("beforeDisconnect",function(a){z9("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){m9()&&(m9(),D9(null))});
D9(c)},L9=function(){var a=g.$i();
if(!a)return null;var b=r9().wd();return g.di(b,a)},M9=function(a){g.Iz("remote",a)},N9=function(){var a=m9();
return!!a&&3!=a.getProxyState()},O9=function(){t9()?k9().stopSession():v9("stopSession called before API ready.");
var a=m9();a&&(a.disconnect(1),D9(null))},P9=function(){var a;
a=r9().Jc.$_gos();var b=F9();b&&m9()&&(g.ci(a,b)||a.push(b));return nra(a)},S9=function(a,b){g.Gn.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.MB;this.A=this.o=null;this.H=(0,g.z)(this.KE,this);this.F=(0,g.z)(this.Hi,this);this.G=(0,g.z)(this.JE,this);this.J=(0,g.z)(this.TE,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Dp,this),Q9(this))):c=3;0!=c&&(b?this.Dp(c):g.Qg((0,g.z)(function(){this.Dp(c)},this),0));
var d=H9();d&&R9(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},T9=function(a){return new g.RB(a.B.getPlayerContextData())},W9=function(a,b,c,d,e){var f=T9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.VB(f,b,d);g.p(c)&&(g.TB(f,c),l.currentTime=c);g.p(k)&&(l.listId=k);U9(a,"setPlaylist",l);e||V9(a,f)},Q9=function(a){(0,g.H)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.B(this.KG,a),this))},a)},X9=function(a){(0,g.H)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},Y9=function(a,b){50>a.C.xc()&&g.OB(a.C,b)},Z9=function(a,b,c){var d=T9(a);
g.TB(d,c);-1E3!=d.g&&(d.g=b);V9(a,d)},U9=function(a,b,c){a.B.sendMessage(b,c)},V9=function(a,b){X9(a);
a.B.setPlayerContextData(g.WB(b));Q9(a)},R9=function(a,b){a.A&&(a.A.removeUpdateListener(a.H),a.A.removeMediaListener(a.F),a.Hi(null));
a.A=b;a.A&&($9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.H),a.A.addMediaListener(a.F),a.A.media.length&&a.Hi(a.A.media[0]))},ora=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=T9(a);b.contentId!=d.videoId&&$9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.TB(d,a.o.getEstimatedTime());V9(a,d)}else $9("No cast media video. Ignoring state update.")},$9=function(a){g.Iz("CP",a)},a$=function(a,b,c){return(0,g.z)(function(a){this.Qb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Qb("Retrying "+b+" using MDx browser channel."),U9(this,b,c))},a)},pra=function(a){var b=!1;
k9()||(a=new g.mA(a),a.subscribe("yt-remote-cast2-availability-change",function(a){g.Vi("yt-remote-cast-available",a);z9("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){i9("onReceiverSelected: "+a.friendlyName);
g.Vi("yt-remote-cast-receiver",a);z9("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){i9("onReceiverResumed: "+a.friendlyName);
g.Vi("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){i9("onSessionChange: "+g.$h(a));
a||g.Xi("yt-remote-cast-receiver");z9("yt-remote-cast2-session-change",a)}),g.ka("yt.mdx.remote.cloudview.instance_",a,void 0),b=!0);
i9("cloudview.createSingleton_: "+b);return b},qra=function(){var a=0<=g.dc.search(/\ (CrMo|Chrome|CriOS)\//);
return g.pi||a},b$=function(a,b){t9()?k9().setConnectedScreenStatus(a,b):v9("setConnectedScreenStatus called before ready.")},rra=function(){i9("clearCurrentReceiver");
g.Xi("yt-remote-cast-receiver")},sra=function(){if(0<=window.navigator.userAgent.indexOf("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){I9();a({command:"cast.sender.init"});return}}if(window.chrome)if(I9(),a=window.navigator.userAgent,0<=a.indexOf("Android")&&0<=a.indexOf("Chrome/")&&window.navigator.presentation){var a="",b=g.vz();55<=b?a="55":50<=b&&(a="50");g.Cz("//www.gstatic.com/eureka/clank"+a+g.Az,g.zz)}else g.Dz(0);else g.zz()},tra=function(a){a?(g.Vi("yt-remote-session-app",a.app),g.Vi("yt-remote-session-name",a.name)):(g.Xi("yt-remote-session-app"),g.Xi("yt-remote-session-name"));
g.ka("yt.mdx.remote.channelParams_",a,void 0)},ura=function(){var a=B9();
if(g.Sb(a)){var a=g.Zi(),b=g.Wi("yt-remote-session-name")||"",c=g.Wi("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.ka("yt.mdx.remote.channelParams_",a,void 0)}},vra=function(){var a=L9();
a?(M9("Resume connection to: "+g.$h(a)),K9(a,0)):(g.ij(),rra(),M9("Skipping connecting because no session screen found."))},wra=function(a){M9("remote.onCastSessionChange_: "+g.$h(a));
if(a){var b=F9();b&&b.id==a.id?b$(b.id,"YouTube TV"):(b&&O9(),K9(a,1))}else m9()&&O9()},xra=function(){var a=P9(),b=F9();
b||(b=L9());return g.Va(a,function(a){return b&&g.Xh(b,a.key)?!0:!1})},yra=function(){var a=g.Wi("yt-remote-cast-receiver");
return a?a.friendlyName:null},zra=function(a,b,c,d){qra()?pra(b)&&(s9(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?G9(a,c):(window.__onGCastApiAvailable=function(b,d){b?G9(a,c):(v9("Failed to load cast API: "+d),u9(!1),s9(!1),g.Xi("yt-remote-cast-available"),g.Xi("yt-remote-cast-receiver"),y9(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):mra():sra())):i9("Cannot initialize because not running Chrome")},Ara=
function(a){this.B=this.A="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Nf(a)||"";b&&(this.B=":"+b);this.A=g.Mf(a)||"";a=g.dc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ma(a,"10.0")&&(this.o=!1))},c$=function(a,b,c){g.L.call(this);
this.H=a;this.Z=b;b.addEventListener("onVolumeChange",this.Pk,this);b.addEventListener("onCaptionsTrackListChanged",this.Mu,this);b.addEventListener("captionschanged",this.Bu,this);b.addEventListener("captionssettingschanged",this.bp,this);b.addEventListener("videoplayerreset",this.Ki,this);b.addEventListener("mdxautoplaycancel",this.Kr,this);this.C=!1;this.g=c;c.isDisposed();c.subscribe("proxyStateChange",this.Zu,this);c.subscribe("remotePlayerChange",this.Ji,this);c.subscribe("remoteQueueChange",
this.Ki,this);c.subscribe("autoplayUpNext",this.zu,this);c.subscribe("previousNextChange",this.Wu,this);c.subscribe("nowAutoplaying",this.Pu,this);c.subscribe("autoplayDismissed",this.yu,this);this.suggestion=null;this.D=new g.kl(64);this.o=new g.Hd(this.cw,500,this);g.M(this,this.o);this.A=new g.Hd(this.dw,1E3,this);g.M(this,this.A);this.B={};this.G=new g.Hd(this.ow,1E3,this);g.M(this,this.G);this.F=new g.Rr(this.JL,1E3,this);g.M(this,this.F);this.J=g.w;this.bp();this.Ki();this.Ji()},d$=function(a,
b){var c=a.H,d=a.Z.getVideoData().lengthSeconds;
c.H=b||0;c.g.Qa("progresssync",b,d)},Bra=function(a){d$(a,0);
a.o.stop();e$(a,new g.kl(64))},h$=function(a,b){if(f$(a)&&!a.C){var c=null;
b&&(c={style:a.Z.jj()},g.Yb(c,b));a.g.Xv(g$(a),c);a.B=T9(a.g).o}},i$=function(a,b){var c=a.Z.ne();
c?W9(a.g,g$(a),b,c.g,c.listId.toString()):W9(a.g,g$(a),b);e$(a,new g.kl(1))},Cra=function(a,b){if(b){var c=a.Z.Ec("captions","tracklist",{Wt:1});
c&&c.length?(a.Z.Ze("captions","track",b),a.C=!1):(a.Z.Hp("captions"),a.C=!0)}else a.Z.Ze("captions","track",{})},f$=function(a){return T9(a.g).videoId==g$(a)},g$=function(a){return a.Z.getVideoData().videoId},e$=function(a,b){a.A.stop();
var c=a.D;if(b.o!=c.o||b.g!=c.g){var d=g.T(b,2);if(d!=g.T(a.D,2)){var e=a.Z;(e=g.Nl(e.app,e.playerType||1))&&g.KX(e,d)}a.D=b;Dra(a.H,c,b)}},j$=function(){var a=xra();
!a&&w9()&&yra()&&(a={key:"cast-selector-receiver",name:yra()});return a},Era=function(){var a=P9();
w9()&&g.Wi("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Fra=function(a){var b={device:"Desktop",
app:"youtube-desktop"};g.Ti&&hra();g.bj();J9||(J9=new Ara,g.kj()&&(J9.g="/api/loungedev"));C9||(C9=g.u("yt.mdx.remote.deferredProxies_")||[],g.ka("yt.mdx.remote.deferredProxies_",C9,void 0));ura();var c=r9();if(!c){var d=new g.Zz(J9);g.ka("yt.mdx.remote.screenService_",d,void 0);c=r9();zra(a,d,function(a){a?p9()&&b$(p9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){z9("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript))}b&&!g.u("yt.mdx.remote.initialized_")&&
(g.ka("yt.mdx.remote.initialized_",!0,void 0),M9("Initializing: "+g.lf(b)),k$.push(g.yi("yt-remote-cast2-availability-change",function(){z9("yt-remote-receiver-availability-change")})),k$.push(g.yi("yt-remote-cast2-receiver-selected",function(){n9(null);
z9("yt-remote-auto-connect","cast-selector-receiver")})),k$.push(g.yi("yt-remote-cast2-receiver-resumed",function(){z9("yt-remote-receiver-resumed","cast-selector-receiver")})),k$.push(g.yi("yt-remote-cast2-session-change",wra)),k$.push(g.yi("yt-remote-connection-change",function(a){a?b$(p9(),"YouTube TV"):L9()||(b$(null,null),rra())})),a=B9(),b.isAuto&&(a.id+="#dial"),g.Em("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,M9(" -- with channel params: "+g.lf(a)),tra(a),
c.start(),p9()||vra())},l$=function(){w9()?k9()?t9()?(i9("Requesting cast selector."),k9().requestSession()):(i9("Wait for cast API to be ready to request the session."),x9.push(g.yi("yt-remote-cast2-api-ready",l$))):v9("requestCastSelector: Cast is not initialized."):v9("requestCastSelector: Cast API is not installed!")},m$=function(a){g.hz.call(this,a);
this.A={key:g.bi(),name:g.Q("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.kl(64);this.H=0},Dra=function(a,b,c){a.F=c;
a.g.Qa("presentingplayerstatechange",new g.hC(c,b))},n$=function(a,b,c){if(b.key!=a.B.key)if(b.key==a.A.key)O9();
else{a.B=b;var d;if(!c){c=a.g.ne();d=a.g.getVideoData().videoId;var e;if(c){e=[];for(var f=0;f<c.B;f++)e[f]=c.Pb(f).videoId}else e=[a.g.getVideoData().videoId];d={videoIds:e,listId:a.g.Xe(),videoId:d,index:Math.max(a.g.Sw(),0),currentTime:a.g.getCurrentTime()}}a=d;M9("Connecting to: "+g.lf(b));"cast-selector-receiver"==b.key?(n9(a||null),b=a||null,t9()?k9().setLaunchParams(b):v9("setLaunchParams called before ready.")):!a&&N9()&&p9()==b.key?z9("yt-remote-connection-change",!0):(O9(),n9(a||null),a=
r9().wd(),(b=g.di(a,b.key))&&K9(b,1))}};
g.C(h9,g.Mz);g.h=h9.prototype;g.h.wd=function(a){return this.Jc.$_gs(a)};
g.h.contains=function(a){return!!this.Jc.$_c(a)};
g.h.get=function(a){return this.Jc.$_g(a)};
g.h.start=function(){this.Jc.$_st()};
g.h.Il=function(a,b,c){this.Jc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Jc.$_r(a,b,c)};
g.h.xl=function(a,b,c,d){this.Jc.$_un(a,b,c,d)};
g.h.R=function(){for(var a=0,b=this.o.length;a<b;++a)this.Jc.$_ubk(this.o[a]);this.o.length=0;this.Jc=null;h9.M.R.call(this)};
g.h.FJ=function(){this.aa("screenChange")};
g.h.qG=function(){this.aa("onlineScreenChange")};
var q9=null,x9=[],C9=null,J9=null;g.C(S9,g.Gn);g.h=S9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.w,a$(this,"play")):U9(this,"play"),Z9(this,1,g.UB(T9(this))),this.aa("remotePlayerChange")):Y9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.w,a$(this,"pause")):U9(this,"pause"),Z9(this,2,g.UB(T9(this))),this.aa("remotePlayerChange")):Y9(this,this.pause)};
g.h.Hw=function(a){if(1==this.g){if(this.o){var b=T9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.gb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.w,a$(this,"seekTo",{newTime:a}))}else U9(this,"seekTo",{newTime:a});Z9(this,3,a);this.aa("remotePlayerChange")}else Y9(this,g.B(this.Hw,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.w,a$(this,"stopVideo")):U9(this,"stopVideo");var a=T9(this);a.index=-1;a.videoId="";g.SB(a);V9(this,a);this.aa("remotePlayerChange")}else Y9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=T9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){$9("set receiver volume: "+d)},this),(0,g.z)(function(){this.Qb("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){$9("set receiver muted: "+b)},this),(0,g.z)(function(){this.Qb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);U9(this,"setVolume",e)}c.muted=b;c.volume=a;V9(this,c)}else Y9(this,g.B(this.setVolume,a,b))};
g.h.Xv=function(a,b){if(1==this.g){var c=T9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.lf(b.style),g.Yb(d,c.o));U9(this,"setSubtitlesTrack",d);V9(this,c)}else Y9(this,g.B(this.Xv,a,b))};
g.h.Cp=function(a,b){if(1==this.g){U9(this,"setAudioTrack",{videoId:a,audioTrackId:b.zc.id});var c=T9(this);c.audioTrackId=b.zc.id;V9(this,c)}else Y9(this,g.B(this.Cp,a,b))};
g.h.Gw=function(a,b){if(1==this.g){if(a&&b){var c=T9(this);g.VB(c,a,b);V9(this,c)}U9(this,"previous")}else Y9(this,g.B(this.Gw,a,b))};
g.h.Fw=function(a,b){if(1==this.g){if(a&&b){var c=T9(this);g.VB(c,a,b);V9(this,c)}U9(this,"next")}else Y9(this,g.B(this.Fw,a,b))};
g.h.ts=function(){1==this.g?U9(this,"dismissAutoplay"):Y9(this,this.ts)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.aa("proxyStateChange",a,this.g)}S9.M.dispose.call(this)};
g.h.R=function(){X9(this);this.B=null;this.C.clear();R9(this,null);S9.M.R.call(this)};
g.h.Dp=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.aa("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.PB(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.KG=function(a,b){this.aa(a,b)};
g.h.KE=function(a){if(!a)this.Hi(null),R9(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=T9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)$9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,V9(this,b)}};
g.h.Hi=function(a){$9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),ora(this),this.aa("remotePlayerChange")};
g.h.JE=function(a){a?(ora(this),this.aa("remotePlayerChange")):this.Hi(null)};
g.h.TE=function(){var a=H9();a&&R9(this,a)};
g.h.Qb=function(a){g.Iz("CP",a)};
var k$=[];g.h=Ara.prototype;g.h.lg=function(a,b,c){var d=this.g;if(g.p(c)?c:this.o)d="https://"+this.A+this.B+this.g;return g.Vf(d+a,b||{})};
g.h.Bp=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Db:g.B(this.AJ,c,!0),onError:g.B(this.zJ,d),Uc:g.B(this.BJ,d)};b&&(c.Sb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Fi(a,c)};
g.h.AJ=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.zJ=function(a,b){a(Error("Request error: "+b.status))};
g.h.BJ=function(a){a(Error("request timed out"))};
g.C(c$,g.L);g.h=c$.prototype;
g.h.R=function(){c$.M.R.call(this);this.o.stop();this.A.stop();this.J();this.Z.removeEventListener("onVolumeChange",this.Pk,this);this.Z.removeEventListener("onCaptionsTrackListChanged",this.Mu,this);this.Z.removeEventListener("captionschanged",this.Bu,this);this.Z.removeEventListener("videoplayerreset",this.Ki,this);this.Z.removeEventListener("captionssettingschanged",this.bp,this);this.Z.removeEventListener("mdxautoplaycancel",this.Kr,this);this.g.Ja("proxyStateChange",this.Zu,this);this.g.Ja("remotePlayerChange",
this.Ji,this);this.g.Ja("remoteQueueChange",this.Ki,this);this.g.Ja("autoplayUpNext",this.zu,this);this.g.Ja("previousNextChange",this.Wu,this);this.g.Ja("nowAutoplaying",this.Pu,this);this.g.Ja("autoplayDismissed",this.yu,this);this.g=this.H=null};
g.h.Dx=function(a,b){2==this.g.g||(f$(this)?this.hC.apply(this,arguments):this.eC.apply(this,arguments))};
g.h.Bu=function(a){this.Dx("control_subtitles_set_track",g.Sb(a)?null:a)};
g.h.bp=function(){var a=this.Z.Ec("captions","track");g.Sb(a)||h$(this,a)};
g.h.eC=function(a,b){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":i$(this,this.Z.getCurrentTime());break;case "control_seek":i$(this,c[0]);break;case "control_subtitles_set_track":h$(this,c[0]);break;case "control_set_audio_track":c=c[0],f$(this)&&this.g.Cp(g$(this),c)}};
g.h.hC=function(a,b){if(1081!=T9(this.g).g||"control_seek"!=a){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":T9(this.g).gb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.F.Ug(c[0],c[1]);break;case "control_subtitles_set_track":h$(this,c[0]);break;case "control_set_audio_track":c=c[0],f$(this)&&this.g.Cp(g$(this),c)}}};
g.h.Pk=function(a){if(f$(this)){this.g.Ja("remotePlayerChange",this.Ji,this);var b=Math.round(a.volume);a=!!a.muted;var c=T9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.G.start();this.g.subscribe("remotePlayerChange",this.Ji,this)}};
g.h.Mu=function(){g.Sb(this.B)||Cra(this,this.B);this.C=!1};
g.h.Zu=function(a,b){this.A.stop();2==b&&this.dw()};
g.h.Ji=function(){if(f$(this)){this.o.stop();var a=T9(this.g);switch(a.g){case 1081:e$(this,new g.kl(8));break;case 1:this.cw();e$(this,new g.kl(8));break;case 1083:case 3:e$(this,new g.kl(9));break;case 0:e$(this,new g.kl(2));this.F.stop();d$(this,this.Z.getVideoData().lengthSeconds);break;case 1082:e$(this,new g.kl(4));break;case 2:e$(this,new g.kl(4));d$(this,g.UB(a));break;case -1:e$(this,new g.kl(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.Q("YTP_MDX_PLAYER_ERROR")},e$(this,
new g.kl(128,a))}var a=T9(this.g).o,b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.B=a,Cra(this,a));a=T9(this.g);-1==a.volume||Math.round(this.Z.getVolume())==a.volume&&this.Z.Bd()==a.muted||this.G.isActive()||this.ow()}else Bra(this)};
g.h.Wu=function(){this.Z.Qa("mdxpreviousnextchange")};
g.h.Ki=function(){f$(this)||Bra(this)};
g.h.Kr=function(){this.g.ts()};
g.h.zu=function(a){a&&(a=g.Fi("/watch_queue_ajax",{method:"GET",Cc:{action_get_watch_queue_item:1,video_id:a},Db:(0,g.z)(this.EH,this)}))&&(this.J=(0,g.z)(a.abort,a))};
g.h.EH=function(a,b){var c=new g.Ay({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.Z.Qa("mdxautoplayupnext",c)};
g.h.Pu=function(a){(0,window.isNaN)(a)||this.Z.Qa("mdxnowautoplaying",a)};
g.h.yu=function(){this.Z.Qa("mdxautoplaycanceled")};
g.h.JL=function(a,b){-1==T9(this.g).g?i$(this,a):b&&this.g.Hw(a)};
g.h.ow=function(){if(f$(this)){var a=T9(this.g);this.Z.removeEventListener("onVolumeChange",this.Pk,this);a.muted?this.Z.mute():this.Z.rf();this.Z.setVolume(a.volume);this.Z.addEventListener("onVolumeChange",this.Pk,this)}};
g.h.cw=function(){this.o.stop();if(!this.g.isDisposed()){var a=T9(this.g);a.gb()&&e$(this,new g.kl(8));d$(this,g.UB(a));this.o.start()}};
g.h.dw=function(){this.A.stop();this.o.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.A.start()};
g.C(m$,g.hz);g.h=m$.prototype;g.h.create=function(){Fra("embedded"==g.V(this.g).g);this.D.push(g.yi("yt-remote-before-disconnect",this.GE,this));this.D.push(g.yi("yt-remote-connection-change",this.SG,this));this.D.push(g.yi("yt-remote-receiver-availability-change",this.Xu,this));this.D.push(g.yi("yt-remote-auto-connect",this.QG,this));this.D.push(g.yi("yt-remote-receiver-resumed",this.PG,this));this.Xu()};
g.h.load=function(){this.g.Tm();m$.M.load.call(this);this.C=new c$(this,this.g,this.o);var a;a=(a=E9())?a.currentTime:0;var b=N9()?new S9(m9(),void 0):null;0==a&&b&&(a=g.UB(T9(b)));0!=a&&(this.H=a||0,this.g.Qa("progresssync",a,void 0));Dra(this,this.F,this.F);g.g5(this.g.app,6)};
g.h.unload=function(){this.g.Qa("mdxautoplaycanceled");this.B=this.A;g.Cb(this.C,this.o);this.o=this.C=null;m$.M.unload.call(this);g.g5(this.g.app,5)};
g.h.R=function(){g.zi(this.D);m$.M.R.call(this)};
g.h.lj=function(a,b){this.loaded&&this.C.Dx.apply(this.C,arguments)};
g.h.KB=function(){return this.loaded?this.C.suggestion:null};
g.h.wx=function(){return this.o?T9(this.o).L:!1};
g.h.hasNext=function(){return this.o?T9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.jL=function(){var a=T9(this.o),b=this.g.getVideoData(),c=g.gm(this.g),d=b.clipEnd,b=b.clipStart,e=this.getCurrentTime(),f=a.getDuration(),k;k=a.H?a.B+((0,g.G)()-a.A)/1E3:a.B;var l=1>=g9(a)-this.getCurrentTime(),m=a.J,n=g9(a),a=0<a.C?a.C+((0,g.G)()-a.A)/1E3:a.C;return{allowSeeking:c,clipEnd:d,clipStart:b,current:e,displayedStart:-1,duration:f,ingestionTime:k,isPeggedToLive:l,loaded:m,seekableEnd:n,seekableStart:a}};
g.h.kL=function(){this.o&&this.o.Fw()};
g.h.lL=function(){this.o&&this.o.Gw()};
g.h.GE=function(a){1==a&&(this.J=this.o?T9(this.o):null)};
g.h.SG=function(){var a=N9()?new S9(m9(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Bb(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.getVideoData().videoId&&this.g.Fc(g.UB(a)));this.g.Qa("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.Xu=function(){this.G=[this.A].concat(Era());var a=j$()||this.A;n$(this,a,!this.loaded);this.g.ya("onMdxReceiversChange")};
g.h.QG=function(){var a=j$();n$(this,a)};
g.h.PG=function(){this.B=j$()};
g.h.iL=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?l$():n$(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&l$(),!0):!1}};
g.h.mL=function(){U9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Ue=function(){return!1};
window._exportCheck==g.wa&&g.ka("ytmod.player.remote",m$,void 0);})(_yt_player);
